In [66]:
data = ''.join(open('in.txt').read().split('->')).splitlines()
data

['476,63  481,63',
 '478,93  478,87  478,93  480,93  480,90  480,93  482,93  482,83  482,93  484,93  484,88  484,93  486,93  486,83  486,93  488,93  488,90  488,93  490,93  490,87  490,93',
 '489,96  489,98  482,98  482,101  496,101  496,98  494,98  494,96',
 '489,96  489,98  482,98  482,101  496,101  496,98  494,98  494,96',
 '478,93  478,87  478,93  480,93  480,90  480,93  482,93  482,83  482,93  484,93  484,88  484,93  486,93  486,83  486,93  488,93  488,90  488,93  490,93  490,87  490,93',
 '500,146  505,146',
 '478,93  478,87  478,93  480,93  480,90  480,93  482,93  482,83  482,93  484,93  484,88  484,93  486,93  486,83  486,93  488,93  488,90  488,93  490,93  490,87  490,93',
 '474,50  474,42  474,50  476,50  476,42  476,50  478,50  478,46  478,50  480,50  480,45  480,50  482,50  482,44  482,50',
 '510,165  510,155  510,165  512,165  512,160  512,165  514,165  514,161  514,165  516,165  516,158  516,165  518,165  518,157  518,165',
 '487,29  487,33  480,33  480,37  499,37  499,33

In [67]:
import numpy as np
class Playground:
    def __init__(self):
        self.playground = np.zeros((200,200))
        self.current = [0,0]
        self.source = self.setup_source()

    dict={
        0:'air',
        1:'rock',
        2:'sand',
        3:'source'
    }

    def setup_source(self):
        self.playground.T[100][0] = '3'
        return [100,0]

    def setup_rocks(self,x,y):
        if self.current == [0,0]:
            self.current=[x,y]
            self.playground.T[x][y] = 1
        else:
            #move x
            if self.current[1]-(y) == 0:
                if self.current[0]-(x) < 0:
                    self.playground[y][self.current[0]:x+1] = 1
                    self.current[0]=x
                else:
                    self.playground[y][x:self.current[0]+1] = 1
                    self.current[0]=x

            #move y
            if self.current[0]-(x) == 0:
                if self.current[1]-(y) <0:
                    self.playground.T[self.current[0]][self.current[1]:y+1] = 1
                    self.current[1] = y
                else:
                    self.playground.T[self.current[0]][y:self.current[1]+1] = 1
                    self.current[1] = y

    def drop_sand(self):
        sandx=self.source[0]
        sandy=self.source[1]
        while True:
            # we check if there is smth to suport the sand
            #if there is somthing bellow
            if(self.playground.T[sandx][sandy+1]) ==0:
                sandy+=1
            elif(self.playground.T[sandx][sandy+1]) == 2:
                #check left
                if self.playground.T[sandx-1][sandy+1] < 1:
                    sandx -=1
                    sandy +=1
                #check right
                elif self.playground.T[sandx+1][sandy+1] <1 :
                    sandx +=1
                    sandy +=1
                else:
                    self.playground.T[sandx][sandy] = 2
                    break

            elif(self.playground.T[sandx][sandy+1]) == 1:
                #check left
                if self.playground.T[sandx-1][sandy+1] < 1:
                    sandx -=1
                    sandy +=1
                #check right
                elif self.playground.T[sandx+1][sandy+1] <1 :
                    sandx +=1
                    sandy +=1
                else:
                    self.playground.T[sandx][sandy] = 2
                    break
                #check right

In [68]:
p = Playground()
import re
for row in data:
    nums = re.findall('\d+',row)
    p.current = [0,0]
    for i in range(0,len(nums),2):
        x = int(nums[i])-400
        y = int(nums[i+1])
        p.setup_rocks(x,y)
p.playground

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [69]:
i=0
while True:
    try:
        p.drop_sand()
    except:
        break
    i+=1
print(i)
p.playground

618


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# Part 1 Done

In [70]:
data = ''.join(open('in.txt').read().split('->')).splitlines()
data

['476,63  481,63',
 '478,93  478,87  478,93  480,93  480,90  480,93  482,93  482,83  482,93  484,93  484,88  484,93  486,93  486,83  486,93  488,93  488,90  488,93  490,93  490,87  490,93',
 '489,96  489,98  482,98  482,101  496,101  496,98  494,98  494,96',
 '489,96  489,98  482,98  482,101  496,101  496,98  494,98  494,96',
 '478,93  478,87  478,93  480,93  480,90  480,93  482,93  482,83  482,93  484,93  484,88  484,93  486,93  486,83  486,93  488,93  488,90  488,93  490,93  490,87  490,93',
 '500,146  505,146',
 '478,93  478,87  478,93  480,93  480,90  480,93  482,93  482,83  482,93  484,93  484,88  484,93  486,93  486,83  486,93  488,93  488,90  488,93  490,93  490,87  490,93',
 '474,50  474,42  474,50  476,50  476,42  476,50  478,50  478,46  478,50  480,50  480,45  480,50  482,50  482,44  482,50',
 '510,165  510,155  510,165  512,165  512,160  512,165  514,165  514,161  514,165  516,165  516,158  516,165  518,165  518,157  518,165',
 '487,29  487,33  480,33  480,37  499,37  499,33

In [71]:
import numpy as np
class Playground:
    def __init__(self,size):
        self.playground = np.zeros((size+3,700))
        self.current = [0,0]
        self.source = self.setup_source()

    dict={
        0:'air',
        1:'rock',
        2:'sand',
        3:'source'
    }

    def setup_source(self):
        self.playground.T[500][0] = 3
        self.playground[-1] = 1
        return [500,0]

    def setup_rocks(self,x,y):
        if self.current == [0,0]:
            self.current=[x,y]
            self.playground.T[x][y] = 1
        else:
            #move x
            if self.current[1]-(y) == 0:
                if self.current[0]-(x) < 0:
                    self.playground[y][self.current[0]:x+1] = 1
                    self.current[0]=x
                else:
                    self.playground[y][x:self.current[0]+1] = 1
                    self.current[0]=x

            #move y
            if self.current[0]-(x) == 0:
                if self.current[1]-(y) <0:
                    self.playground.T[self.current[0]][self.current[1]:y+1] = 1
                    self.current[1] = y
                else:
                    self.playground.T[self.current[0]][y:self.current[1]+1] = 1
                    self.current[1] = y

    def drop_sand(self):
        sandx=self.source[0]
        sandy=self.source[1]
        while True:
            # we check if there is smth to suport the sand
            #if there is somthing bellow
            if(self.playground.T[sandx][sandy+1]) ==0:
                sandy+=1
            elif(self.playground.T[sandx][sandy+1]) == 2:
                #check left
                if self.playground.T[sandx-1][sandy+1] < 1:
                    sandx -=1
                    sandy +=1
                #check right
                elif self.playground.T[sandx+1][sandy+1] <1 :
                    sandx +=1
                    sandy +=1
                else:
                    self.playground.T[sandx][sandy] = 2
                    break

            elif(self.playground.T[sandx][sandy+1]) == 1:
                #check left
                if self.playground.T[sandx-1][sandy+1] < 1:
                    sandx -=1
                    sandy +=1
                #check right
                elif self.playground.T[sandx+1][sandy+1] <1 :
                    sandx +=1
                    sandy +=1
                else:
                    self.playground.T[sandx][sandy] = 2
                    break
                #check right
        if sandx == self.source[0] and self.source[1] == sandy:
            return True
        else: return False

# Finding the Y

In [85]:
max_y = 0
import re
for row in data:
    nums = re.findall('\d+',row)
    for i in range(0,len(nums),2):
        y = int(nums[i+1])
        if y>max_y:
            max_y=y
print(max_y)

165


In [86]:
p = Playground(max_y)
import re
for row in data:
    nums = re.findall('\d+',row)
    p.current = [0,0]
    for i in range(0,len(nums),2):
        x = int(nums[i])
        y = int(nums[i+1])
        p.setup_rocks(x,y)

In [87]:
i=0
while True:
    try:
        flag = p.drop_sand()
    except:
        break
    i+=1
    if flag:break
print(i)
p.playground

26358


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 1., 1.]])